apiVersion: v1
kind: Secret
metadata:
  name: device-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: http://10.20.0.70:32080/root/device-homeomorphisx.git
