apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- github.com/argoproj/argo-events/manifests/base
- github.com/argoproj/argo-events/manifests/cluster-install/rbac
- event-bus.yaml
- operate-workflow-rbac.yaml 
namespace: argo-events
