apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api
  namespace: production
spec:
  selector:
    matchLabels:
      app: myapp
      type: gateway-api
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
        type: gateway-api
    spec:
      containers:
      - name: gateway-api
        image: 10.20.0.70:32443/library/gateway-api:0.1-SNAPSHOT
        imagePullPolicy: "Always"
        ports:
        - containerPort: 4000
        env: 
          - name: ENV_TYPE
            value: production
#      imagePullSecrets:
#      - name: harbor-registry-secret
