apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: production
spec:
  selector:
    app: myapp
    type: gateway-api
  type: NodePort
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 31700
