apiVersion: v1
kind: Service
metadata:
  name: iam-service
  namespace: production
spec:
  selector:
    app: myapp
    type: iam
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31601
