apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-webapp
  namespace: production
spec:
  selector:
    matchLabels:
      app: myapp
      type: user-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
        type: user-webapp
    spec:
      containers:
      - name: activity
        image: 10.20.0.70:32443/library/user-webapp:0.1-SNAPSHOT
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        env: 
          - name: ENV_TYPE
            value: production
#      imagePullSecrets:
#      - name: harbor-registry-secret
