apiVersion: v1
kind: Service
metadata:
  name: user-webapp-service
  namespace: production
spec:
  selector:
    app: myapp
    type: user-webapp
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31705
