apiVersion: v1
kind: ConfigMap
metadata:
    # if you want to use this config map by default - name it "artifact-repositories" 
  name: artifact-repositories
  namespace: workflows
  annotations:
    # v3.0 and after - if you want to use a specific key, put that key into this annotation 
    workflows.argoproj.io/default-artifact-repository: default-v1
data:
  default-v1: |
    git:
      repo: http://10.20.0.70:32080/root/device-homeomorphisx.git
      usernameSecret:
        name: github-access
        key: user
      passwordSecret:
        name: github-access
        key: token
