apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-artifact-volume
  annotations:
    pv.kubernetes.io/provisioned-by: iiidevops-nfs-provisioner
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: iiidevops-nfs-storage
  nfs:
    path: /iiidevopsNFS/maven-repo
    server: 10.20.0.70
