apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: run-acceptence-test-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: test
  serviceAccountName: workflow
  templates:
  - name: test
    dag:
      tasks:
      - name: build
        templateRef:
          name: java-acceptence-test
          template: acceptence-test

