apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: container-image
spec:
  templates:
  - name: build-kaniko-git
    inputs:
      parameters:
      - name: service
      - name: container_image
      - name: container_tag
      artifacts:
      - name: gitsource
        path: /src/
        git:
          repo: http://10.20.0.70:32080/root/device-homeomorphisx.git
          usernameSecret:
            name: github-access
            key: user
          passwordSecret:
            name: github-access
            key: token
    container:
      image: gcr.io/kaniko-project/executor:debug
      command: [/kaniko/executor]
      args:
      - '--dockerfile=/src/{{inputs.parameters.service}}/Dockerfile'
      - '--context=/var/maven/org/ninox'
      - '--build-arg=JARFILE={{inputs.parameters.service}}/1.0-SNAPSHOT/{{inputs.parameters.service}}-1.0-SNAPSHOT.jar'
      - '--destination={{inputs.parameters.container_image}}:{{inputs.parameters.container_tag}}'
      - '--skip-tls-verify'
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker/
        - name: maven-repo
          mountPath: /var/maven
