apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: java-acceptence-test
  namespace: workflows
spec:
  imagePullScrets:
  - name: harbor-registry-secret
  artifactRepositoryRef:
    configMap: artifact-repositories
    key: default-v1
  templates:
  - name: acceptence-test
    inputs:
      artifacts: 
      - name: gitsource
        path: /src/
        git:
          repo: http://10.20.0.70:32080/root/device-homeomorphisx.git
          usernameSecret:
            name: github-access
            key: user
          passwordSecret:
            name: github-access
            key: token
    volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}
    - name: maven-repo
      persistentVolumeClaim:
        claimName: maven-artifact-pvc
    containerSet:
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
        - name: dind-socket
          mountPath: /var/run/
        - name: maven-repo
          mountPath: /var/maven
      containers:
        - name: dind
          image: docker:20.10.12-dind
          securityContext:
            privileged: true
          command: [/usr/local/bin/dockerd-entrypoint.sh]
        - name: observability-connector
          image: 10.20.0.70:32443/library/observability-connector:0.1-SNAPSHOT
          env:
            - name: ENV_TYPE
              value: dev
          command: [java]
          args:
          - -jar
          - java-application.jar
        - name: hono-service
          image: 10.20.0.70:32443/library/hono-service:0.1-SNAPSHOT
          env:
            - name: ENV_TYPE
              value: dev
          command: [java]
          args:
          - -jar
          - java-application.jar
        - name: activity-service
          image: 10.20.0.70:32443/library/activity-service:0.1-SNAPSHOT
          env:
            - name: ENV_TYPE
              value: dev
          command: [java]
          args:
          - -jar
          - java-application.jar
        - name: iam-service
          image: 10.20.0.70:32443/library/iam-service:0.1-SNAPSHOT
          env:
            - name: ENV_TYPE
              value: dev
          command: [java]
          args:
          - -jar
          - java-application.jar
        - name: gateway-api
          image: 10.20.0.70:32443/library/gateway-api:0.1-SNAPSHOT
          env:
            - name: ENV_TYPE
              value: dev
          command: [java]
          args:
          - -jar
          - java-application.jar
        - name: user-webapp
          image: 10.20.0.70:32443/library/user-webapp:0.1-SNAPSHOT
          env:
            - name: ENV_TYPE
              value: dev
            - name: REACT_APP_ENV_TYPE
              value: dev
          command: [java]
          args:
          - -jar
          - java-application.jar
        - name: main
          image: maven:3.8.4-openjdk-11
       #   dependencies:
      #      - dind
     #       - observability-connector
    #        - hono-service
   #         - activity-service
  #          - iam-service
 #           - gateway-api
#            - user-webapp
          command: [/usr/bin/mvn]
          args:
          - test
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2376
          workingDir: /src/bdd-acceptence-test
